framework:
    messenger:
        #failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            insert_async: "%env(MESSENGER_TRANSPORT_DSN)%"
            # sync: 'sync://'

        # buses:
        #     messenger.bus.default: []

        routing:
        #     Symfony\Component\Mailer\Messenger\SendEmailMessage: async
        #     Symfony\Component\Notifier\Message\ChatMessage: async
        #     Symfony\Component\Notifier\Message\SmsMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\InsertFreelanceJeanPaulMessage': insert_async
            'App\Message\InsertFreelanceLinkedInMessage': insert_async
