services:  

  php:
      user: "${USER_ID}:${GROUP_ID}"
      build: ./docker/php
      volumes:
        - .:/var/www:delegated
      depends_on:
        - database
        - elasticsearch
      networks:
        - app_network

  nginx:
      build: ./docker/nginx
      ports:
        - "8000:80"
      volumes:
        - ./public:/var/www/public:delegated
      depends_on:
        - php
      networks:
        - app_network

  database:
      image: mariadb:10.7.3
      environment:
        MARIADB_USER: root
        MARIADB_ROOT_PASSWORD: root
        MARIADB_DATABASE: app
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "no"
      volumes:
        - database_data:/var/lib/mysql:rw
        - ./var/mysql:/var/www/var
      networks:
        - app_network
        
  adminer:
      image: adminer
      depends_on:
        - database
      environment:
        APP_ENV: dev
        #ADMINER_DESIGN: pepa-linha
        ADMINER_DEFAULT_SERVER:
      ports:
        - "8082:8080"
      networks:
        - app_network

  #rabbitmq:
    # image: rabbitmq:3-management
    # ports:
    # - 15676:15672

    
  elasticsearch:  
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.26
      ports:
        - 9200:9200
        - 9300:9300
      environment:
        - discovery.type=single-node
      networks:
        - app_network
      # - http.port=9200
      # - ES_JAVA_OPTS=-Xms2g -Xmx8g
networks:
  app_network:

volumes:
  database_data: