services:
  mysql:
    image: mysql:8
    command: --max_allowed_packet=325058560 --lower_case_table_names=2
    volumes:
      - .docker-dev/.data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test-technique
      - MYSQL_PASSWORD=root
    ports:
      - 3344:3306

  app:
    build: .docker-dev/app
    ports:
      - 8000:8000
    environment:
      - IS_DOCKER=1
    links:
      - mysql
    volumes:
      - .:/var/application

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15676:15672

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    ports:
      - 9201:9200
    environment:
      - discovery.type=single-node
      - http.port=9200
      - ES_JAVA_OPTS=-Xms2g -Xmx8g
