# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

#Ne pas modifier ni ajouter manuellement IS_DOCKER
    is_docker: "%env(bool:IS_DOCKER)%"

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Elasticsearch\Client:
        factory: ['Elasticsearch\ClientBuilder', 'create']
        calls:
            - method: setHosts
              arguments:
                -
                  - '%env(ELASTICSEARCH_URL)%'
            - method: build


            # makes classes in src/ available to be used as services
    # this creates a service per c=lass whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # Pa besoin de controller à voir selon les besoins 
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
